name: zego_uikit
description: ZegoUIKit is a low-code offering with pre-built and UI-ready components, such as AudioVideoView, CameraButtons, etc. Save time and assemble features fast with ZegoUIKit.
version: 2.22.2
homepage: https://www.zegocloud.com/

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_plugin_adapter: ^2.11.5

  zego_express_engine: ^3.13.3
  zego_zpns: any
  zego_callkit: any

  encrypt: ^5.0.3
  permission_handler: ^11.0.1
  flutter_logs: ^2.1.11
  native_device_orientation: ^1.2.1
  wakelock_plus: ^1.1.3
  cached_network_image: ^3.3.0
  file_picker: ^6.0.0
  path: ^1.8.3
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0 # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any
  lints: ^3.0.0

flutter:
  assets:
    - assets/icons/
  plugin:
    platforms:
      android:
        package: com.zegocloud.uikit.zego_uikit_plugin
        pluginClass: ZegoUikitPlugin
      ios:
        pluginClass: ZegoUikitPlugin
